### PR TITLE
Add migration

### PR DESCRIPTION
**Pull request by dfrankow**

### CODE REVIEW

**Comment by dfrankow** [comment]
Whoops, I meant to add this PR on my forked repo. I haven't tested it yet.

**Comment by dfrankow** [comment]
Okay, this works to address #6.

**Comment by dfrankow** [comment]
I'd squash-merge this commit, as I moved things around until I got it right.

**Comment by dfrankow** [comment]
FYI, on a different note: I don't plan to use this project because it is GPL v3, and I would want it for commercial use.

I support your right to use GPL v3, so best wishes.

If you decide to change the license to something more permissive (e.g., MIT, BSD, Apache, ..), I would be interested.

Best wishes.

**Comment by vishalanandl177** [comment]
Thanks, Dan

I changed the license to MIT. Please update to the new version 1.0.5

*Regards,*
Vishal Anand,
Technical Lead,
LinkedIn <https://www.linkedin.com/in/vishal-anand-530ba0b5/> | M:
+91-8009417767

**Comment by dfrankow** [comment]
Excellent, thank you!

I decided I probably should log all requests, DRF or not. Is your library actually DRF-specific? It looks like it would log anything.

**Comment by vishalanandl177** [comment]
That's true until request type is application/json.

**Pull request merged**
