### PR TITLE
Added request user and response size to logs, added sensitive data masking to request url

### PR DESCRIPTION
**Pull request by Guichardsantiago**

### CODE REVIEW

**Comment by vishale6x** [comment]
Hi @Guichardsantiago,

Sorry to inform you but I can't approve your merge request.
We can't add user as a part of the log. Because we are exposing the user's info into the logs.
As per my discussion with some enterprises, this can cause some issues.

**Comment by vishalanandl177** [comment]
Hi @Guichardsantiago,

Sorry to inform you but I can't approve your merge request.
We can't add user as a part of the log. Because we are exposing the user's info into the logs.
As per my discussion with some enterprises, this can cause some issues.

**Comment by Guichardsantiago** [comment]
@vishalanandl177 what if we put as an optional feature like the many others you have, and being off by default

**Comment by SirbitoX** [comment]
Hi @vishalanandl177, would you please let us know when you will deploy this feature?
I'm asking because if you don't have any plan to deploy it soon, I should add this functionality myself somehow.

**Pull request closed without merging**
